-- Telescope bindings
map("n", "<leader>tt", "<Cmd>Telescope treesitter<cr>", { noremap = true })
map("n", "<leader>tf", "<Cmd>Telescope find_files<cr>", { noremap = true })
map("n", "<leader>tz", "<Cmd>Telescope colorscheme<cr>", { noremap = true })
map("n", "<leader>th", "<Cmd>Telescope help_tags<cr>", { noremap = true })
map("n", "<leader>tqf", "<Cmd>Telescope quickfix<cr>", { noremap = true })
map("n", "<leader>tm", "<Cmd>Telescope marks<cr>", { noremap = true })
map("n", "<leader>td", '<Cmd>lua require("telescope.builtin").diagnostics({bufnr=0})<cr>', { noremap = true })
map("n", "<leader>tr", "<Cmd>Telescope lsp_references<cr>", { noremap = true })
map("n", "<leader>tb", "<Cmd>Telescope buffers<cr>", { noremap = true })
map("n", "<leader>tk", "<Cmd>Telescope keymaps<cr>", { noremap = true })
map("n", "<leader>tg", "<Cmd>Telescope grep_string<cr>", { noremap = true })
map("v", "<leader>tg", '"zy<Cmd>Telescope grep_string default_text=<C-r>z<cr>', { noremap = true })
map("n", "<leader>tt", "<Cmd>Telescope highlights<cr>", { noremap = true })
