require('noiz.plugins.nvim_tree')
require('noiz.plugins.barbar')
require('noiz.plugins.orgmode')
require('noiz.plugins.prettier')
require('noiz.plugins.feline')
require('noiz.plugins.treesitter')
require('colorizer').setup()
